#!/usr/bin/env ruby

# Video Game Prices v 0.7
# Arad Reed
# Add console to display (necessary to differentiate games)
# Number search results and add option to open page in browser (selecting number)

require 'optparse'
require 'mechanize'

def header
    printf("%-50s%-10s%-10s%-10s\n", "Title", "Loose", "Complete", "New")
    80.times {print "-"}
    puts
end

def printGame(title, loose_price, new_price, complete_price = 0)
  # Display the game info in a moderately pretty format
  if (title.length > 40)
    title = "#{title[0, 40]} (...)" 
  end
  
  printf("%-50s%-10s%-10s%-10s\n", title, loose_price, complete_price, new_price)
end

# Switches
options = {}

optparse = OptionParser.new do |opts|   
  opts.banner = "Usage: ./gamePrices [options] video game" 
  
  opts.on( '-p', '--platform  "PLATFORM"', 'Search on a specific platform (quotes if platform contains spaces)' ) do |p| 
    consoles = ["amiibo", "atari 2600", "atari 400", "atari 5200", "atari 7800", "cd-i", "gameboy", "gameboy advance", "gameboy color", "gamecube", "macintosh", "nes", "nintendo 3ds", "nintendo 64", "nintendo ds", "pc games", "sega genesis", "super nintendo", "virtual boy", "wii", "wii u"]   
    p.downcase!
    
    if (consoles.include? p) 
      options[:platform] = p
    else
      puts "Platform argument is invalid"
    end
      
    ARGV.delete(p)
  end
  
  opts.on( '-h', '--help', 'Display this screen' ) do     
    puts opts     
    exit   
  end
end

optparse.parse!

# Game search
game = ARGV.join("+")
link = "http://videogames.pricecharting.com/search?q=#{game}&type=videogames&go=Go"

mech = Mechanize.new

page = mech.get(link)

# If the link is still the same, we're on the search page. Otherwise, we're on the game's page
if (page.uri.to_s == link) 
  # Display all search results
  # Game array, containing all the data that needs parsed for each game
  # Split by artbitrary number of whitespace (games are separated by more whitespace than game data)
  games = page.search('//table[@id="games_table"]/tbody/tr').text.strip.split(/\s{30,}/)
  
  # Begin display
  header
  
  games.each do |game| 
    # Gives Title, Console, Genre, Loose Price, New Price
    game_data = game.strip.split(/\s{2,}/)
    
    if (options[:platform] == game_data[1].downcase)
      printGame(game_data[0].strip, game_data[3].strip, game_data[4].strip)
    end
  end
  
else
  # Specific game page
  title = page.at('//h1[@id="product_name"]').text.split(/prices/i)[0].strip
  loose_price = page.at('//td[@id="used_price"]').text.strip
  new_price = page.at('//td[@id="new_price"]').text.strip
  complete_price = page.at('//td[@id="complete_price"]').text.strip
  
  header
  printGame(title, loose_price, new_price, complete_price)
end